# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/youenn/Documents/0-Work/SimQJ_project/SimQJ_project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/youenn/Documents/0-Work/SimQJ_project/SimQJ_project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/opt/homebrew/bin/ctest $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/youenn/Documents/0-Work/SimQJ_project/SimQJ_project/CMakeFiles /Users/youenn/Documents/0-Work/SimQJ_project/SimQJ_project//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/youenn/Documents/0-Work/SimQJ_project/SimQJ_project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named core

# Build rule for target.
core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 core
.PHONY : core

# fast build rule for target.
core/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/build
.PHONY : core/fast

#=============================================================================
# Target rules for targets named simQJ

# Build rule for target.
simQJ: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 simQJ
.PHONY : simQJ

# fast build rule for target.
simQJ/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simQJ.dir/build.make CMakeFiles/simQJ.dir/build
.PHONY : simQJ/fast

#=============================================================================
# Target rules for targets named Catch2

# Build rule for target.
Catch2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Catch2
.PHONY : Catch2

# fast build rule for target.
Catch2/fast:
	$(MAKE) $(MAKESILENT) -f _deps/catch2-build/src/CMakeFiles/Catch2.dir/build.make _deps/catch2-build/src/CMakeFiles/Catch2.dir/build
.PHONY : Catch2/fast

#=============================================================================
# Target rules for targets named Catch2WithMain

# Build rule for target.
Catch2WithMain: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Catch2WithMain
.PHONY : Catch2WithMain

# fast build rule for target.
Catch2WithMain/fast:
	$(MAKE) $(MAKESILENT) -f _deps/catch2-build/src/CMakeFiles/Catch2WithMain.dir/build.make _deps/catch2-build/src/CMakeFiles/Catch2WithMain.dir/build
.PHONY : Catch2WithMain/fast

#=============================================================================
# Target rules for targets named unit_tests

# Build rule for target.
unit_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unit_tests
.PHONY : unit_tests

# fast build rule for target.
unit_tests/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/unit_tests.dir/build.make tests/CMakeFiles/unit_tests.dir/build
.PHONY : unit_tests/fast

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simQJ.dir/build.make CMakeFiles/simQJ.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simQJ.dir/build.make CMakeFiles/simQJ.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simQJ.dir/build.make CMakeFiles/simQJ.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/models/ising_model.o: src/models/ising_model.cpp.o
.PHONY : src/models/ising_model.o

# target to build an object file
src/models/ising_model.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/models/ising_model.cpp.o
.PHONY : src/models/ising_model.cpp.o

src/models/ising_model.i: src/models/ising_model.cpp.i
.PHONY : src/models/ising_model.i

# target to preprocess a source file
src/models/ising_model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/models/ising_model.cpp.i
.PHONY : src/models/ising_model.cpp.i

src/models/ising_model.s: src/models/ising_model.cpp.s
.PHONY : src/models/ising_model.s

# target to generate assembly for a file
src/models/ising_model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/models/ising_model.cpp.s
.PHONY : src/models/ising_model.cpp.s

src/output_data.o: src/output_data.cpp.o
.PHONY : src/output_data.o

# target to build an object file
src/output_data.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/output_data.cpp.o
.PHONY : src/output_data.cpp.o

src/output_data.i: src/output_data.cpp.i
.PHONY : src/output_data.i

# target to preprocess a source file
src/output_data.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/output_data.cpp.i
.PHONY : src/output_data.cpp.i

src/output_data.s: src/output_data.cpp.s
.PHONY : src/output_data.s

# target to generate assembly for a file
src/output_data.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/output_data.cpp.s
.PHONY : src/output_data.cpp.s

src/sim_math.o: src/sim_math.cpp.o
.PHONY : src/sim_math.o

# target to build an object file
src/sim_math.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/sim_math.cpp.o
.PHONY : src/sim_math.cpp.o

src/sim_math.i: src/sim_math.cpp.i
.PHONY : src/sim_math.i

# target to preprocess a source file
src/sim_math.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/sim_math.cpp.i
.PHONY : src/sim_math.cpp.i

src/sim_math.s: src/sim_math.cpp.s
.PHONY : src/sim_math.s

# target to generate assembly for a file
src/sim_math.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/sim_math.cpp.s
.PHONY : src/sim_math.cpp.s

src/simulation.o: src/simulation.cpp.o
.PHONY : src/simulation.o

# target to build an object file
src/simulation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/simulation.cpp.o
.PHONY : src/simulation.cpp.o

src/simulation.i: src/simulation.cpp.i
.PHONY : src/simulation.i

# target to preprocess a source file
src/simulation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/simulation.cpp.i
.PHONY : src/simulation.cpp.i

src/simulation.s: src/simulation.cpp.s
.PHONY : src/simulation.s

# target to generate assembly for a file
src/simulation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/src/simulation.cpp.s
.PHONY : src/simulation.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... Catch2"
	@echo "... Catch2WithMain"
	@echo "... core"
	@echo "... simQJ"
	@echo "... unit_tests"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/models/ising_model.o"
	@echo "... src/models/ising_model.i"
	@echo "... src/models/ising_model.s"
	@echo "... src/output_data.o"
	@echo "... src/output_data.i"
	@echo "... src/output_data.s"
	@echo "... src/sim_math.o"
	@echo "... src/sim_math.i"
	@echo "... src/sim_math.s"
	@echo "... src/simulation.o"
	@echo "... src/simulation.i"
	@echo "... src/simulation.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

